global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    scrape_interval: 5s

    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: mqtt-exporter

    static_configs:
      - targets: ["mqtt-exporter:9000"]

    metric_relabel_configs:
      - source_labels: [sensor]
        regex: 'zigbee2mqtt_(.*)'
        replacement: '$1'
        target_label: sensor
